"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const persona_1 = require("./persona");
const mail_1 = require("./mail");
const direccion_1 = require("./direccion");
const telefono_1 = require("./telefono");
const direccionPaloma = new direccion_1.Direccion("Calle Mariah Carey", 23, 3, "B", "28050", "Madrid", "Madrid");
const mailPaloma = new mail_1.Mail("personal", "Paloma@gmail.com");
const telefonoPaloma = new telefono_1.Telefono("móvil", 676435433);
const direccionRoberto = new direccion_1.Direccion("Calle Toledo", 16, 1, "A", "28343", "Valdemoro", "Madrid");
const mailRoberto = new mail_1.Mail("personal", "Roberto@gmail.com");
const telefonoRoberto = new telefono_1.Telefono("móvil", 687245433);
const direccionTeresa = new direccion_1.Direccion("Calle Pilar Rubio", 45, 6, "C", "28330", "San Martín de la Vega", "Madrid");
const mailTeresa = new mail_1.Mail("personal", "Teresa@gmail.com");
const telefonoTeresa = new telefono_1.Telefono("móvil", 776488433);
const datosPaloma = new persona_1.Persona('Paloma', 'Romero Verde', 47, '56787495S', new Date(1975, 2, 10), 'amarillo', 'mujer', [direccionPaloma], [mailPaloma], [telefonoPaloma], "Su piso se encuentra en venta");
const datosRoberto = new persona_1.Persona('Robero', 'Guerra Blanco', 31, '045676354P', new Date(1991, 1, 1), 'azul', 'hombre', [direccionRoberto], [mailRoberto], [telefonoRoberto], "Compra de vehículo");
const datosTeresa = new persona_1.Persona('Teresa', 'Robles Torres', 60, '33231212P', new Date(1962, 0, 9), 'naranja', 'mujer', [direccionTeresa], [mailTeresa], [telefonoTeresa], "Piso en alquiler");
console.log("Datos antes de realizar cambios:");
console.log(datosPaloma);
console.log(datosRoberto);
console.log(datosTeresa);
const datos = new Array(datosPaloma, datosRoberto, datosTeresa);
const buscarDNI = "33231212P";
const editarPersona = datos.find(persona => persona.dni === buscarDNI);
const nuevaDireccion = new direccion_1.Direccion("Calle María Moliner", 44, 5, "D", "28342", "Valdemoro", "Madrid");
const nuevoMail = new mail_1.Mail("trabajo", "ide.morena.blanco@gmail.com");
const nuevoTelefono = new telefono_1.Telefono("fijo", 918763421);
editarPersona.agregarDireccion(nuevaDireccion);
editarPersona.agregarMail(nuevoMail);
editarPersona.agregarTelefono(nuevoTelefono);
console.log("Datos tras realizar los cambios:");
console.log(datosPaloma);
console.log(datosRoberto);
console.log(datosTeresa);
